import { QueryInterface, DataTypes, QueryTypes } from 'sequelize';

/** @type {import('sequelize-cli').Migration} */
module.exports = {
  up: (queryInterface: QueryInterface): Promise<void> => queryInterface.sequelize.transaction(
    async (transaction) => {
      /**
       * Add seed commands here.
       *
       * Example:
       * await queryInterface.bulkInsert('People', [{
       *   name: 'John Doe',
       *   isBetaMember: false
       * }], {});
      */
      await queryInterface.bulkInsert('mst_dropdown_values', [
        { name: 'SERUM CREATININE', key: "serum_creatinine", type: 'Test', is_enabled: true },
        { name: 'LDH', key: "ldh", type: 'Test', is_enabled: true },
        { name: 'BLOOD OXYGEN SATURATION', key: "blood_oxygen_saturation", type: 'Test', is_enabled: true },
        { name: 'CBC: HB/WBC/RBC PLATELET', key: "cbc_hb_wbc_rbc_platelet", type: 'Test', is_enabled: true },
        { name: 'BLOOD SUGAR: F AND PP', key: "blood_sugar_f_and_pp", type: 'Test', is_enabled: true },
        { name: 'UREA AND CREATININE TEST', key: "urea_and_creatinine_test", type: 'Test', is_enabled: true },
        { name: 'SERUM SODIUM AND POTASSIUM', key: "serum_sodium_and_potassium", type: 'Test', is_enabled: true },
        { name: 'PREGNANCY TEST', key: "pregnancy_test", type: 'Test', is_enabled: true },
        { name: 'LIVER FUNCTION TEST: BILIRUBIN AND LIVER ENZYMES (SGOT/SGPT/SAKP)', key: "liver_function_test", type: 'Test', is_enabled: true },
        { name: 'THYROID FUNCTION TEST (T3/T4/TSH)', key: "thyroid_function_test", type: 'Test', is_enabled: true },
        { name: 'URINE: ROUTINE AND MICROSCOPIC ANC CULTURE', key: "urine_routine_and_microscopic_anc_culture", type: 'Test', is_enabled: true },
        { name: 'STOOL: OCCULT BLOOD AND MICROSCOPIC FOR CYSTS ETC. AND CULTURE', key: "stool_occult_blood_and_microscopic", type: 'Test', is_enabled: true },
        { name: 'WIDAL TEST (TYPHOID FEVER)', key: "widal_test", type: 'Test', is_enabled: true },
        { name: 'SERUM CALCIUM', key: "serum_calcium", type: 'Test', is_enabled: true },
        { name: 'SERUM VIT. D3', key: "serum_vit_d3", type: 'Test', is_enabled: true },
        { name: 'SERUM ALBUMIN AND GLOBULIN', key: "serum_albumin_and_globulin", type: 'Test', is_enabled: true },
        { name: 'TROPONIN - T', key: "troponin_t", type: 'Test', is_enabled: true },
        { name: 'URINE MICROALBUMINURIA', key: "urine_microalbuminuria", type: 'Test', is_enabled: true },
        { name: 'TB PCR', key: "tb_pcr", type: 'Test', is_enabled: true },
        { name: 'MALARIA - ANTIGEN/ANTOBODY/PARASITE DETECTION', key: "malaria_antigen_antibody_parasite_detection", type: 'Test', is_enabled: true },
        { name: 'DENGUE', key: "dengue", type: 'Test', is_enabled: true },
        { name: 'COAGULATION PROFILE (PT/APTT)', key: "coagulation_profile_pt_aptt", type: 'Test', is_enabled: true },
        { name: 'BLOOD GROUP AND RH', key: "blood_group_and_rh", type: 'Test', is_enabled: true },
        { name: 'RHEUMATOID FACTOR/ANTI-NUCLEAR FACTOR/HLA B27', key: "rheumatoid_factor_anti_nuclear_factor_hla_b27", type: 'Test', is_enabled: true },
        { name: 'FEVER PANEL: PYREXIA OF UNKNOWN ORIGIN VIRAL/BACTERIAL/PARASITIC', key: "fever_panel", type: 'Test', is_enabled: true },
        { name: 'SERUM IRON AND VIT. B12', key: "serum_iron_and_vit_b12", type: 'Test', is_enabled: true },
        { name: 'CERVICAL SPINE X-RAY PA AND LATERAL VIEW', key: "cervical_spine_x_ray_pa_and_lateral_view", type: 'Test', is_enabled: true },
        { name: 'THORACIC SPINE X-RAY PA AND LATERAL VIEW', key: "thoracic_spine_x_ray_pa_and_lateral_view", type: 'Test', is_enabled: true },
        { name: 'LUMBOSACCRAL SPINE X-RAY PA AND LATERAL VIEW', key: "lumbosacral_spine_x_ray_pa_and_lateral_view", type: 'Test', is_enabled: true },
        { name: 'KNEE JOINT X-RAY PA AND LATERAL VIEW', key: "knee_joint_x_ray_pa_and_lateral_view", type: 'Test', is_enabled: true },
        { name: 'SHOULDER JOINT X-RAY PA AND LATERAL VIEW', key: "shoulder_joint_x_ray_pa_and_lateral_view", type: 'Test', is_enabled: true },
        { name: 'ANKLE JOINT X-RAY PA AND LATERAL VIEW', key: "ankle_joint_x_ray_pa_and_lateral_view", type: 'Test', is_enabled: true },
        { name: 'PELVIC ULTRASOUND', key: "pelvic_ultrasound", type: 'Test', is_enabled: true },
        { name: 'CRP', key: "crp", type: 'Test', is_enabled: true },
        { name: 'IL 6', key: "il_6", type: 'Test', is_enabled: true },
        { name: 'Ferritin', key: "ferritin", type: 'Test', is_enabled: true },
        { name: 'Procalcitonin', key: "procalcitonin", type: 'Test', is_enabled: true },
        { name: 'Troponin I', key: "troponin_i", type: 'Test', is_enabled: true },
        { name: 'BT', key: "bt", type: 'Test', is_enabled: true },
        { name: 'CT Scan', key: "ct_scan", type: 'Test', is_enabled: true },
        { name: 'PT', key: "pt", type: 'Test', is_enabled: true },
        { name: 'APTT', key: "aptt", type: 'Test', is_enabled: true },
        { name: 'HRCT', key: "hrct", type: 'Test', is_enabled: true },
        { name: 'RTPCR (Covid)', key: "rtpcr_covid", type: 'Test', is_enabled: true },
        { name: 'RAT (Covid)', key: "rat_covid", type: 'Test', is_enabled: true },
        { name: 'TEST', key: "test", type: 'Test', is_enabled: true },

        { name: 'GALLSTONES', key: 'gallstones', type: 'Diagnosis', is_enabled: true },
        { name: 'BRONCHITIS, ACUTE', key: 'bronchitis_acute', type: 'Diagnosis', is_enabled: true },
        { name: 'DIARRHEA, AMOEBIASIS', key: 'diarrhea_amoebiasis', type: 'Diagnosis', is_enabled: true },
        { name: 'PNEUMONIA, TUBERCULOUS', key: 'pneumonia_tuberculous', type: 'Diagnosis', is_enabled: true },
        { name: 'PREGNANCY, TERMINATION', key: 'pregnancy_termination', type: 'Diagnosis', is_enabled: true },
        { name: 'URINARY TRACT INFECTION', key: 'urinary_tract_infection', type: 'Diagnosis', is_enabled: true },
        { name: 'TUBERCULOSIS', key: 'tuberculosis', type: 'Diagnosis', is_enabled: true },
        { name: 'CATARACT', key: 'cataract', type: 'Diagnosis', is_enabled: true },
        { name: 'TOXICITY, NOT OTHERWISE SPECIFIED', key: 'toxicity_not_otherwise_specified', type: 'Diagnosis', is_enabled: true },
        { name: 'RESPIRATORY TRACT INFECTION, UPPER', key: 'respiratory_tract_infection_upper', type: 'Diagnosis', is_enabled: true },
        { name: 'LACERATION', key: 'laceration', type: 'Diagnosis', is_enabled: true },
        { name: 'OTITIS MEDIA', key: 'otitis_media', type: 'Diagnosis', is_enabled: true },
        { name: 'MASTITIS', key: 'mastitis', type: 'Diagnosis', is_enabled: true },
        { name: 'CONJUNCTIVITIS', key: 'conjunctivitis', type: 'Diagnosis', is_enabled: true },
        { name: 'HEAD INJURY', key: 'head_injury', type: 'Diagnosis', is_enabled: true },
        { name: 'PUERPERAL SEPSIS', key: 'puerperal_sepsis', type: 'Diagnosis', is_enabled: true },
        { name: 'DENTAL CARIES', key: 'dental_caries', type: 'Diagnosis', is_enabled: true },
        { name: 'SCABIES', key: 'scabies', type: 'Diagnosis', is_enabled: true },
        { name: 'TINEA CAPITIS', key: 'tinea_capitis', type: 'Diagnosis', is_enabled: true },
        { name: 'BRONCHITIS', key: 'bronchitis', type: 'Diagnosis', is_enabled: true },
        { name: 'INJURY', key: 'injury', type: 'Diagnosis', is_enabled: true },
        { name: 'EPILEPSY', key: 'epilepsy', type: 'Diagnosis', is_enabled: true },
        { name: 'BITE, DOG', key: 'bite_dog', type: 'Diagnosis', is_enabled: true },
        { name: 'GASTROENTERITIS', key: 'gastroenteritis', type: 'Diagnosis', is_enabled: true },
        { name: 'CHOLERA', key: 'cholera', type: 'Diagnosis', is_enabled: true },
        { name: 'HELMINTHIASIS', key: 'helminthiasis', type: 'Diagnosis', is_enabled: true },
        { name: 'CANDIDIASIS', key: 'candidiasis', type: 'Diagnosis', is_enabled: true },
        { name: 'SEIZURE', key: 'seizure', type: 'Diagnosis', is_enabled: true },
        { name: 'DEPRESSION', key: 'depression', type: 'Diagnosis', is_enabled: true },
        { name: 'SINUSITIS', key: 'sinusitis', type: 'Diagnosis', is_enabled: true },
        { name: 'TOXICITY, FOOD', key: 'toxicity_food', type: 'Diagnosis', is_enabled: true },
        { name: 'PERIPHERAL NEUROPATHY', key: 'peripheral_neuropathy', type: 'Diagnosis', is_enabled: true },
        { name: 'LARYNGITIS', key: 'laryngitis', type: 'Diagnosis', is_enabled: true },
        { name: 'TINEA CORPORIS', key: 'tinea_corporis', type: 'Diagnosis', is_enabled: true },
        { name: 'VARICELLA', key: 'varicella', type: 'Diagnosis', is_enabled: true },
        { name: 'CHALAZION', key: 'chalazion', type: 'Diagnosis', is_enabled: true },
        { name: 'CEREBRAL PALSY', key: 'cerebral_palsy', type: 'Diagnosis', is_enabled: true },
        { name: 'CONJUNCTIVITIS, ALLERGIC', key: 'conjunctivitis_allergic', type: 'Diagnosis', is_enabled: true },
        { name: 'RESPIRATORY TRACT INFECTION, LOWER', key: 'respiratory_tract_infection_lower', type: 'Diagnosis', is_enabled: true },
        { name: 'GASTROESOPHAGEAL REFLUX DISEASE', key: 'gastroesophageal_reflux_disease', type: 'Diagnosis', is_enabled: true },
        { name: 'CHRONIC OBSTRUCTIVE PULMONARY DISEASE', key: 'chronic_obstructive_pulmonary_disease', type: 'Diagnosis', is_enabled: true },
        { name: 'MYCOBACTERIUM TUBERCULOSIS, EXTRAPULMONARY', key: 'mycobacterium_tuberculosis_extrapulmonary', type: 'Diagnosis', is_enabled: true },
        { name: 'FAILURE TO THRIVE', key: 'failure_to_thrive', type: 'Diagnosis', is_enabled: true },
        { name: 'POLIOMYELITIS', key: 'poliomyelitis', type: 'Diagnosis', is_enabled: true },
        { name: 'CANDIDIASIS, ORAL', key: 'candidiasis_oral', type: 'Diagnosis', is_enabled: true },
        { name: 'Acute pain', key: 'acute_pain', type: 'Diagnosis', is_enabled: true },
        { name: 'Gastritis', key: 'gastritis', type: 'Diagnosis', is_enabled: true },
        { name: 'Urinary incontinence', key: 'urinary_incontinence', type: 'Diagnosis', is_enabled: true },
        { name: 'Trachoma', key: 'trachoma', type: 'Diagnosis', is_enabled: true },
        { name: 'Sexually transmitted disease', key: 'sexually_transmitted_disease', type: 'Diagnosis', is_enabled: true },
        { name: 'Secondary hypertension', key: 'secondary_hypertension', type: 'Diagnosis', is_enabled: true },
        { name: 'Schizophrenia', key: 'schizophrenia', type: 'Diagnosis', is_enabled: true },
        { name: 'Post-traumatic stress disorder', key: 'post_traumatic_stress_disorder', type: 'Diagnosis', is_enabled: true },
        { name: 'Pneumonia', key: 'pneumonia', type: 'Diagnosis', is_enabled: true },
        { name: 'Phlebitis and thrombophlebitis', key: 'phlebitis_thrombophlebitis', type: 'Diagnosis', is_enabled: true },
        { name: 'Otitis externa', key: 'otitis_externa', type: 'Diagnosis', is_enabled: true },
        { name: 'Multiple gestation', key: 'multiple_gestation', type: 'Diagnosis', is_enabled: true },
        { name: 'Meningitis', key: 'meningitis', type: 'Diagnosis', is_enabled: true },
        { name: 'Malaria', key: 'malaria', type: 'Diagnosis', is_enabled: true },
        { name: 'Kwashiorkor', key: 'kwashiorkor', type: 'Diagnosis', is_enabled: true },
        { name: 'Herpes Zoster', key: 'herpes_zoster', type: 'Diagnosis', is_enabled: true },
        { name: 'Hemorrhage in early pregnancy', key: 'hemorrhage_in_early_pregnancy', type: 'Diagnosis', is_enabled: true },
        { name: 'Gonorrhea', key: 'gonorrhea', type: 'Diagnosis', is_enabled: true },
        { name: 'Encephalocele', key: 'encephalocele', type: 'Diagnosis', is_enabled: true },
        { name: 'Dysuria', key: 'dysuria', type: 'Diagnosis', is_enabled: true },
        { name: 'Dystonia', key: 'dystonia', type: 'Diagnosis', is_enabled: true },
        { name: 'Dysphagia', key: 'dysphagia', type: 'Diagnosis', is_enabled: true },
        { name: 'Electrolyte or Fluid Disorder', key: 'electrolyte_or_fluid_disorder', type: 'Diagnosis', is_enabled: true },
        { name: 'Disorder of Ear', key: 'disorder_of_ear', type: 'Diagnosis', is_enabled: true },
        { name: 'Diabetes Mellitus', key: 'diabetes_mellitus', type: 'Diagnosis', is_enabled: true },
        { name: 'Dermatomycosis', key: 'dermatomycosis', type: 'Diagnosis', is_enabled: true },
        { name: 'Decubitus Ulcer', key: 'decubitus_ulcer', type: 'Diagnosis', is_enabled: true },
        { name: 'Cardiac Dysrhythmia', key: 'cardiac_dysrhythmia', type: 'Diagnosis', is_enabled: true },
        { name: 'Complication of puerperium', key: 'complication_of_puerperium', type: 'Diagnosis', is_enabled: true },
        { name: 'Bacterial Infection', key: 'bacterial_infection', type: 'Diagnosis', is_enabled: true },
        { name: 'Asthma', key: 'asthma', type: 'Diagnosis', is_enabled: true },
        { name: 'Disorder of joint', key: 'disorder_of_joint', type: 'Diagnosis', is_enabled: true },
        { name: 'Cholera due to Vibrio Cholerae', key: 'cholera_due_to_vibrio_cholerae', type: 'Diagnosis', is_enabled: true },
        { name: 'Vitamin A Deficiency with Keratomalacia', key: 'vitamin_a_deficiency_with_keratomalacia', type: 'Diagnosis', is_enabled: true },
        { name: 'Viral conjunctivitis', key: 'viral_conjunctivitis', type: 'Diagnosis', is_enabled: true },
        { name: 'Urethrorrhoea', key: 'urethrorrhoea', type: 'Diagnosis', is_enabled: true },
        { name: 'Perineal laceration during delivery', key: 'perineal_laceration_during_delivery', type: 'Diagnosis', is_enabled: true },
        { name: 'Umbilical hemorrhage after birth', key: 'umbilical_hemorrhage_after_birth', type: 'Diagnosis', is_enabled: true },
        { name: 'Trichuriasis', key: 'trichuriasis', type: 'Diagnosis', is_enabled: true },
        { name: 'Tetanus neonatorum', key: 'tetanus_neonatorum', type: 'Diagnosis', is_enabled: true },
        { name: 'Tetanus', key: 'tetanus', type: 'Diagnosis', is_enabled: true },
        { name: 'Syncope and collapse', key: 'syncope_and_collapse', type: 'Diagnosis', is_enabled: true },
        { name: 'Superficial injury of shoulder and upper arm', key: 'superficial_injury_of_shoulder_and_upper_arm', type: 'Diagnosis', is_enabled: true },
        { name: 'Superficial injury of forearm', key: 'superficial_injury_of_forearm', type: 'Diagnosis', is_enabled: true },
        { name: 'Spina Bifida', key: 'spina_bifida', type: 'Diagnosis', is_enabled: true },
        { name: 'Retention of urine', key: 'retention_of_urine', type: 'Diagnosis', is_enabled: true },
        { name: 'Pulp and periapical tissue disease', key: 'pulp_and_periapical_tissue_disease', type: 'Diagnosis', is_enabled: true },
        { name: 'Positive Serological and/or Viral Culture Findings for Human Immunodeficiency Virus', key: 'positive_serological_and_or_viral_culture_findings_for_hiv', type: 'Diagnosis', is_enabled: true },
        { name: 'Polydactyly', key: 'polydactyly', type: 'Diagnosis', is_enabled: true },
        { name: 'Nutritional Marasmus', key: 'nutritional_marasmus', type: 'Diagnosis', is_enabled: true },
        { name: 'Microcephalus', key: 'microcephalus', type: 'Diagnosis', is_enabled: true },
        { name: 'MEASLES', key: 'measles', type: 'Diagnosis', is_enabled: true },
        { name: 'Lymphogranuloma venereum', key: 'lymphogranuloma_venereum', type: 'Diagnosis', is_enabled: true },
        { name: 'Jaundice', key: 'jaundice', type: 'Diagnosis', is_enabled: true },
        { name: 'Itching', key: 'itching', type: 'Diagnosis', is_enabled: true },
        { name: 'Infection by Taenia', key: 'infection_by_taenia', type: 'Diagnosis', is_enabled: true },
        { name: 'Infection by Strongyloides', key: 'infection_by_strongyloides', type: 'Diagnosis', is_enabled: true },
        { name: 'Hypothermia of newborn', key: 'hypothermia_of_newborn', type: 'Diagnosis', is_enabled: true },
        { name: 'Hyperglycaemia', key: 'hyperglycaemia', type: 'Diagnosis', is_enabled: true },
        { name: 'HUMAN IMMUNODEFICIENCY VIRUS (HIV) DISEASE', key: 'hiv_disease', type: 'Diagnosis', is_enabled: true },
        { name: 'Herpes Simplex', key: 'herpes_simplex', type: 'Diagnosis', is_enabled: true },
        { name: 'Hemorrhoids', key: 'hemorrhoids', type: 'Diagnosis', is_enabled: true },
        { name: 'Headache', key: 'headache', type: 'Diagnosis', is_enabled: true },
        { name: 'Granuloma inguinale', key: 'granuloma_inguinale', type: 'Diagnosis', is_enabled: true },
        { name: 'Glycosuria', key: 'glycosuria', type: 'Diagnosis', is_enabled: true },
        { name: 'Genitourinary tract infection in pregnancy', key: 'genitourinary_tract_infection_in_pregnancy', type: 'Diagnosis', is_enabled: true },
        { name: 'Flushing', key: 'flushing', type: 'Diagnosis', is_enabled: true },
        { name: 'Flatulence, Eructation and Gas Pain', key: 'flatulence_eructation_and_gas_pain', type: 'Diagnosis', is_enabled: true },
        { name: 'Fever', key: 'fever', type: 'Diagnosis', is_enabled: true },
        { name: 'Feeding problems in newborn', key: 'feeding_problems_in_newborn', type: 'Diagnosis', is_enabled: true },
        { name: 'Essential hypertension', key: 'essential_hypertension', type: 'Diagnosis', is_enabled: true },
        { name: 'Enterobiasis', key: 'enterobiasis', type: 'Diagnosis', is_enabled: true },
        { name: 'Shortness of breath', key: 'shortness_of_breath', type: 'Diagnosis', is_enabled: true },
        { name: 'Diabetes Mellitus, Type II', key: 'diabetes_mellitus_type_ii', type: 'Diagnosis', is_enabled: true },
        { name: 'Cough', key: 'cough', type: 'Diagnosis', is_enabled: true },
        { name: 'Convulsions in the newborn', key: 'convulsions_in_the_newborn', type: 'Diagnosis', is_enabled: true },
        { name: 'Chronic Viral Hepatitis', key: 'chronic_viral_hepatitis', type: 'Diagnosis', is_enabled: true },
        { name: 'Chancroid', key: 'chancroid', type: 'Diagnosis', is_enabled: true },
        { name: 'Ascariasis', key: 'ascariasis', type: 'Diagnosis', is_enabled: true },
        { name: 'Angioedema', key: 'angioedema', type: 'Diagnosis', is_enabled: true },
        { name: 'Anaphylaxis', key: 'anaphylaxis', type: 'Diagnosis', is_enabled: true },
        { name: 'Acute Tonsillitis', key: 'acute_tonsillitis', type: 'Diagnosis', is_enabled: true },
        { name: 'Acute Pharyngitis', key: 'acute_pharyngitis', type: 'Diagnosis', is_enabled: true },
        { name: 'Chronic intractable pain', key: 'chronic_intractable_pain', type: 'Diagnosis', is_enabled: true },
        { name: 'Marasmic Kwashiorkor', key: 'marasmic_kwashiorkor', type: 'Diagnosis', is_enabled: true },
        { name: 'Primary Respiratory Tuberculosis, Confirmed Bacteriologically and Histologically', key: 'primary_respiratory_tuberculosis_confirmed_bacteriologically_and_histologically', type: 'Diagnosis', is_enabled: true },
        { name: 'Bacterial foodborne intoxication', key: 'bacterial_foodborne_intoxication', type: 'Diagnosis', is_enabled: true },
        { name: 'Superficial injury of lower limb, level unspecified', key: 'superficial_injury_of_lower_limb_level_unspecified', type: 'Diagnosis', is_enabled: true },
        { name: 'Toxic liver disease', key: 'toxic_liver_disease', type: 'Diagnosis', is_enabled: true },
        { name: 'COVID-19', key: 'covid_19', type: 'Diagnosis', is_enabled: true },
        { name: 'Пневмония', key: 'Pneumony', type: 'Diagnosis', is_enabled: true },
        { name: 'SNAKE BITE', key: 'snake_bite', type: 'Diagnosis', is_enabled: true },
        { name: 'SCORPION STING', key: 'scorpion_sting', type: 'Diagnosis', is_enabled: true },
        { name: 'INSECT BITE', key: 'insect_bite', type: 'Diagnosis', is_enabled: true },
        { name: 'Acute Lymphadenitis', key: 'acute_lymphadenitis', type: 'Diagnosis', is_enabled: true },
        { name: 'ACUTE DIARRHEA', key: 'acute_diarrhea', type: 'Diagnosis', is_enabled: true },
        { name: 'Acute Infectious Diarrhea', key: 'acute_infectious_diarrhea', type: 'Diagnosis', is_enabled: true },
        { name: 'Acute Gastroenteritis', key: 'acute_gastroenteritis', type: 'Diagnosis', is_enabled: true },
        { name: 'Worm Infestation', key: 'worm_infestation', type: 'Diagnosis', is_enabled: true },
        { name: 'Viral Fever', key: 'viral_fever', type: 'Diagnosis', is_enabled: true },
        { name: 'CHRONIC HEPATITIS', key: 'chronic_hepatitis', type: 'Diagnosis', is_enabled: true },
        { name: 'INFECTIOUS HEPATITIS', key: 'infectious_hepatitis', type: 'Diagnosis', is_enabled: true },
        { name: 'Gastro Esophageal Reflux (GER)', key: 'gastro_esophageal_reflux_ger', type: 'Diagnosis', is_enabled: true },
        { name: 'Hookworm Infestation', key: 'hookworm_infestation', type: 'Diagnosis', is_enabled: true },
        { name: 'Pinworm Infestation', key: 'pinworm_infestation', type: 'Diagnosis', is_enabled: true },
        { name: 'Giardiasis', key: 'giardiasis', type: 'Diagnosis', is_enabled: true },
        { name: 'Menstrual Disorder', key: 'menstrual_disorder', type: 'Diagnosis', is_enabled: true },
        { name: 'Menorrhagia', key: 'menorrhagia', type: 'Diagnosis', is_enabled: true },
        { name: 'Meningoencephalitis', key: 'meningoencephalitis', type: 'Diagnosis', is_enabled: true },
        { name: 'Intestinal Obstruction', key: 'intestinal_obstruction', type: 'Diagnosis', is_enabled: true },
        { name: 'Migraine', key: 'migraine', type: 'Diagnosis', is_enabled: true },
        { name: 'Infantile Colic', key: 'infantile_colic', type: 'Diagnosis', is_enabled: true },
        { name: 'Scalds', key: 'scalds', type: 'Diagnosis', is_enabled: true },
        { name: 'Fall Injury', key: 'fall_injury', type: 'Diagnosis', is_enabled: true },
        { name: 'Abrasion', key: 'abrasion', type: 'Diagnosis', is_enabled: true },
        { name: 'Bruise', key: 'bruise', type: 'Diagnosis', is_enabled: true },
        { name: 'Acute Arthritis', key: 'acute_arthritis', type: 'Diagnosis', is_enabled: true },
        { name: 'Chronic Arthritis', key: 'chronic_arthritis', type: 'Diagnosis', is_enabled: true },
        { name: 'Osteoarthritis', key: 'osteoarthritis', type: 'Diagnosis', is_enabled: true },
        { name: 'Hydrocephalus', key: 'hydrocephalus', type: 'Diagnosis', is_enabled: true },
        { name: 'Meningomyelocele', key: 'meningomyelocele', type: 'Diagnosis', is_enabled: true },
        { name: 'Tetany', key: 'tetany', type: 'Diagnosis', is_enabled: true },
        { name: 'Acute Flaccid Paralysis', key: 'acute_flaccid_paralysis', type: 'Diagnosis', is_enabled: true },
        { name: 'Depressive Disorder', key: 'depressive_disorder', type: 'Diagnosis', is_enabled: true },
        { name: 'Anxiety Disorder', key: 'anxiety_disorder', type: 'Diagnosis', is_enabled: true },
        { name: 'Tobacco Addiction', key: 'tobacco_addiction', type: 'Diagnosis', is_enabled: true },
        { name: 'Pustule', key: 'pustule', type: 'Diagnosis', is_enabled: true },
        { name: 'Pressure Sores', key: 'pressure_sores', type: 'Diagnosis', is_enabled: true },
        { name: 'Acne Vulgaris', key: 'acne_vulgaris', type: 'Diagnosis', is_enabled: true },
        { name: 'Tinea Pedis', key: 'tinea_pedis', type: 'Diagnosis', is_enabled: true },
        { name: 'Tinea Unguium', key: 'tinea_unguium', type: 'Diagnosis', is_enabled: true },
        { name: 'Tinea Cruris', key: 'tinea_cruris', type: 'Diagnosis', is_enabled: true },
        { name: 'Severe Acute Malnutrition', key: 'severe_acute_malnutrition', type: 'Diagnosis', is_enabled: true },
        { name: 'Vitamin A Deficiency', key: 'vitamin_a_deficiency', type: 'Diagnosis', is_enabled: true },
        { name: 'Acute Appendicitis', key: 'acute_appendicitis', type: 'Diagnosis', is_enabled: true },
        { name: 'Threatened Abortion', key: 'threatened_abortion', type: 'Diagnosis', is_enabled: true },
        { name: 'Hypothermia', key: 'hypothermia', type: 'Diagnosis', is_enabled: true },
        { name: 'Twin Pregnancy', key: 'twin_pregnancy', type: 'Diagnosis', is_enabled: true },
        { name: 'Umbilical Bleeding of Newborn', key: 'umbilical_bleeding_of_newborn', type: 'Diagnosis', is_enabled: true },
        { name: 'Hemorrhagic Disease of Newborn (HDN)', key: 'hemorrhagic_disease_of_newborn', type: 'Diagnosis', is_enabled: true },
        { name: 'Neonatal Jaundice', key: 'neonatal_jaundice', type: 'Diagnosis', is_enabled: true },
        { name: 'Feeding Difficulty of Newborn', key: 'feeding_difficulty_of_newborn', type: 'Diagnosis', is_enabled: true },
        { name: 'Sepsis', key: 'sepsis', type: 'Diagnosis', is_enabled: true },
        { name: 'Neonatal Seizures', key: 'neonatal_seizures', type: 'Diagnosis', is_enabled: true },
        { name: 'Filariasis', key: 'filariasis', type: 'Diagnosis', is_enabled: true },
        { name: 'Dengue Fever', key: 'dengue_fever', type: 'Diagnosis', is_enabled: true },
        { name: 'Chikungunya Fever', key: 'chikungunya_fever', type: 'Diagnosis', is_enabled: true },
        { name: 'Acute Rhinitis', key: 'acute_rhinitis', type: 'Diagnosis', is_enabled: true },
        { name: 'Pyoderma', key: 'pyoderma', type: 'Diagnosis', is_enabled: true },
        { name: 'Impetigo', key: 'impetigo', type: 'Diagnosis', is_enabled: true },
        { name: 'Acute Suppurative Otitis Media', key: 'acute_suppurative_otitis_media', type: 'Diagnosis', is_enabled: true },
        { name: 'Chronic Suppurative Otitis Media', key: 'chronic_suppurative_otitis_media', type: 'Diagnosis', is_enabled: true },
        { name: 'Acute Urticaria', key: 'acute_urticaria', type: 'Diagnosis', is_enabled: true },
        { name: 'Chronic Urticaria', key: 'chronic_urticaria', type: 'Diagnosis', is_enabled: true },
        { name: 'Papular Urticaria', key: 'papular_urticaria', type: 'Diagnosis', is_enabled: true },
        { name: 'Acid Peptic Disease', key: 'acid_peptic_disease', type: 'Diagnosis', is_enabled: true },
        { name: 'Contusion', key: 'contusion', type: 'Diagnosis', is_enabled: true },
        { name: 'Chronic Wound', key: 'chronic_wound', type: 'Diagnosis', is_enabled: true },
        { name: 'Wound', key: 'wound', type: 'Diagnosis', is_enabled: true },
        { name: 'Ulcer', key: 'ulcer', type: 'Diagnosis', is_enabled: true },
        { name: 'Chronic Ulcer', key: 'chronic_ulcer', type: 'Diagnosis', is_enabled: true },
        { name: 'Acute Bronchiolitis', key: 'acute_bronchiolitis', type: 'Diagnosis', is_enabled: true },
        { name: 'Influenza (Flu)', key: 'influenza_flu', type: 'Diagnosis', is_enabled: true },
        { name: 'Non-Ulcer Dyspepsia (NUD)', key: 'non_ulcer_dyspepsia_nud', type: 'Diagnosis', is_enabled: true },
        { name: 'Aphthous Ulcers', key: 'aphthous_ulcers', type: 'Diagnosis', is_enabled: true },
        { name: 'Febrile Seizures', key: 'febrile_seizures', type: 'Diagnosis', is_enabled: true },
        { name: 'Boil', key: 'boil', type: 'Diagnosis', is_enabled: true },
        { name: 'Functional Constipation', key: 'functional_constipation', type: 'Diagnosis', is_enabled: true },
        { name: 'Anal Fissure', key: 'anal_fissure', type: 'Diagnosis', is_enabled: true },
        { name: 'Tobacco Use Disorder', key: 'tobacco_use_disorder', type: 'Diagnosis', is_enabled: true },
        { name: 'Substance Abuse', key: 'substance_abuse', type: 'Diagnosis', is_enabled: true },
        { name: 'Bipolar Disorder', key: 'bipolar_disorder', type: 'Diagnosis', is_enabled: true },
        { name: 'Alcohol Use Disorder', key: 'alcohol_use_disorder', type: 'Diagnosis', is_enabled: true },
        { name: 'Dental Fluorosis', key: 'dental_fluorosis', type: 'Diagnosis', is_enabled: true },
        { name: 'Gum Abscess', key: 'gum_abscess', type: 'Diagnosis', is_enabled: true },
        { name: 'Glossitis', key: 'glossitis', type: 'Diagnosis', is_enabled: true },
        { name: 'Febrile Blisters', key: 'febrile_blisters', type: 'Diagnosis', is_enabled: true },
        { name: 'Vision Loss', key: 'vision_loss', type: 'Diagnosis', is_enabled: true },
        { name: 'Errors of Refraction', key: 'errors_of_refraction', type: 'Diagnosis', is_enabled: true },
        { name: 'Xerophthalmia', key: 'xerophthalmia', type: 'Diagnosis', is_enabled: true },
        { name: 'Bitots Spots', key: 'bitots_spots', type: 'Diagnosis', is_enabled: true },
        { name: 'Scleritis', key: 'scleritis', type: 'Diagnosis', is_enabled: true },
        { name: 'Strabismus', key: 'strabismus', type: 'Diagnosis', is_enabled: true },
        { name: 'Spring Cattarh', key: 'spring_cattarh', type: 'Diagnosis', is_enabled: true },
        { name: 'Nasal Polyps', key: 'nasal_polyps', type: 'Diagnosis', is_enabled: true },
        { name: 'Deafness', key: 'deafness', type: 'Diagnosis', is_enabled: true },
        { name: 'Defective Vision', key: 'defective_vision', type: 'Diagnosis', is_enabled: true },
        { name: 'Vertigo', key: 'vertigo', type: 'Diagnosis', is_enabled: true },
        { name: 'Low Birth Weight', key: 'low_birth_weight', type: 'Diagnosis', is_enabled: true },
        { name: 'Preterm Baby', key: 'preterm_baby', type: 'Diagnosis', is_enabled: true },
        { name: 'Club Foot', key: 'club_foot', type: 'Diagnosis', is_enabled: true },
        { name: 'Cleft Lip', key: 'cleft_lip', type: 'Diagnosis', is_enabled: true },
        { name: 'Cleft Lip & Cleft Palate', key: 'cleft_lip_and_cleft_palate', type: 'Diagnosis', is_enabled: true },
        { name: 'Hypothyroidism', key: 'hypothyroidism', type: 'Diagnosis', is_enabled: true },
        { name: 'Cracked Nipple', key: 'cracked_nipple', type: 'Diagnosis', is_enabled: true },
        { name: 'Breast Abscess', key: 'breast_abscess', type: 'Diagnosis', is_enabled: true },
        { name: 'Nappy Rash', key: 'nappy_rash', type: 'Diagnosis', is_enabled: true },
        { name: 'Umbilical Cord Infection', key: 'umbilical_cord_infection', type: 'Diagnosis', is_enabled: true },
        { name: 'Atopic Dermatitis', key: 'atopic_dermatitis', type: 'Diagnosis', is_enabled: true },
        { name: 'Vasovagal Syncope', key: 'vasovagal_syncope', type: 'Diagnosis', is_enabled: true },
        { name: 'Orthostatic Syncope', key: 'orthostatic_syncope', type: 'Diagnosis', is_enabled: true },
        { name: 'Postvaccination Fever', key: 'postvaccination_fever', type: 'Diagnosis', is_enabled: true },
        { name: 'Tension Headache', key: 'tension_headache', type: 'Diagnosis', is_enabled: true },
        { name: 'Cluster Headache', key: 'cluster_headache', type: 'Diagnosis', is_enabled: true },
        { name: 'Hand Foot Mouth Disease (HFMD)', key: 'hand_foot_mouth_disease_hfmd', type: 'Diagnosis', is_enabled: true },
        { name: 'Viral Exanthematous Fever', key: 'viral_exanthematous_fever', type: 'Diagnosis', is_enabled: true },
        { name: 'Fracture of Bone', key: 'fracture_of_bone', type: 'Diagnosis', is_enabled: true },
        { name: 'Deformity', key: 'deformity', type: 'Diagnosis', is_enabled: true },

        { name: "CHO", key: "cho", type: "Refer Specialisation", is_enabled: true },
        { name: "MO", key: "mo", type: "Refer Specialisation", is_enabled: true },
        { name: "General Physician", key: "general_physician", type: "Refer Specialisation", is_enabled: true },
        { name: "Obstetrician & Gynecologist", key: "obstetrician_gynecologist", type: "Refer Specialisation", is_enabled: true },
        { name: "Pediatrician", key: "pediatrician", type: "Refer Specialisation", is_enabled: true },
        { name: "General Surgeon", key: "general_surgeon", type: "Refer Specialisation", is_enabled: true },
        { name: "Dermatologist", key: "dermatologist", type: "Refer Specialisation", is_enabled: true },
        { name: "ENT Specialist", key: "ent_specialist", type: "Refer Specialisation", is_enabled: true },
        { name: "Eye Specialist", key: "eye_specialist", type: "Refer Specialisation", is_enabled: true },
        { name: "Dental Surgeon", key: "dental_surgeon", type: "Refer Specialisation", is_enabled: true },

        { name: 'Acetylsalicylic Acid (Aspirin) Tablet 75 mg', key: 'acetylsalicylic_acid_aspirin_tablet_75_mg', type: 'Medication', is_enabled: true },
        { name: 'Albendazole Tablet 400 mg', key: 'albendazole_tablet_400_mg', type: 'Medication', is_enabled: true },
        { name: 'Albendazole Oral Liquid 200 mg/5 ml', key: 'albendazole_oral_liquid_200_mg_5_ml', type: 'Medication', is_enabled: true },
        { name: 'Ambroxol Oral Liquid 30 mg/5 ml', key: 'ambroxol_oral_liquid_30_mg_5_ml', type: 'Medication', is_enabled: true },
        { name: 'Ambroxol Oral Drops 7.5 mg/1 ml', key: 'ambroxol_oral_drops_7_5_mg_1_ml', type: 'Medication', is_enabled: true },
        { name: 'Ambroxol 30 mg+Levosalbutamol 1mg+Guaifensin 50 mg Oral Liquid (5ml)', key: 'ambroxol_30_mg_levosalbutamol_1mg_guaifensin_50_mg_oral_liquid_5ml', type: 'Medication', is_enabled: true },
        { name: 'Ambroxol 7.5 mg+Levosalbutamol 0.25 mg+Guaifensin 12.5 mg Oral Drops (1 ml)', key: 'ambroxol_7_5_mg_levosalbutamol_0_25_mg_guaifensin_12_5_mg_oral_drops_1_ml', type: 'Medication', is_enabled: true },
        { name: 'Amlodipine Tablet 5 mg', key: 'amlodipine_tablet_5_mg', type: 'Medication', is_enabled: true },
        { name: 'Amoxicillin Capsule 250 mg', key: 'amoxicillin_capsule_250_mg', type: 'Medication', is_enabled: true },
        { name: 'Amoxicillin Capsule 500 mg', key: 'amoxicillin_capsule_500_mg', type: 'Medication', is_enabled: true },
        { name: 'Amoxicillin Oral liquid 250 mg/5 ml', key: 'amoxicillin_oral_liquid_250_mg_5_ml', type: 'Medication', is_enabled: true },
        { name: 'Amoxicillin + Clavulanic acid Tablet 625 mg', key: 'amoxicillin_clavulanic_acid_tablet_625_mg', type: 'Medication', is_enabled: true },
        { name: 'Amoxicillin + Clavulanic acid Oral Liquid 228.5 mg/5 ml', key: 'amoxicillin_clavulanic_acid_oral_liquid_228_5_mg_5_ml', type: 'Medication', is_enabled: true },
        { name: 'Ascorbic Acid (Vitamin C) Tablet (Chewable) 500 mg', key: 'ascorbic_acid_vitamin_c_tablet_chewable_500_mg', type: 'Medication', is_enabled: true },
        { name: 'Atorvastatin Tablet 10 mg', key: 'atorvastatin_tablet_10_mg', type: 'Medication', is_enabled: true },
        { name: 'Azithromycin Tablet 500 mg', key: 'azithromycin_tablet_500_mg', type: 'Medication', is_enabled: true },
        { name: 'Azithromycin Oral Liquid 200 mg/5 ml', key: 'azithromycin_oral_liquid_200_mg_5_ml', type: 'Medication', is_enabled: true },
        { name: 'B-Complex (Multivitamin) Capsule', key: 'b_complex_multivitamin_capsule', type: 'Medication', is_enabled: true },
        { name: 'Betamethasone Valerate Cream 0.05%', key: 'betamethasone_valerate_cream_0_05', type: 'Medication', is_enabled: true },
        { name: 'Bevon (Multivitamin) Oral Liquid', key: 'bevon_multivitamin_oral_liquid', type: 'Medication', is_enabled: true },
        { name: 'Bevon (Multivitamin) Oral Drops', key: 'bevon_multivitamin_oral_drops', type: 'Medication', is_enabled: true },
        { name: 'Bisacodyl Tablet 5 mg', key: 'bisacodyl_tablet_5_mg', type: 'Medication', is_enabled: true },
        { name: 'Calamine Lotion', key: 'calamine_lotion', type: 'Medication', is_enabled: true },
        { name: 'Calcium Carbonate Tablet 625 mg', key: 'calcium_carbonate_tablet_625_mg', type: 'Medication', is_enabled: true },
        { name: 'Calcimax P Oral Liquid 150 mg/5 ml', key: 'calcimax_p_oral_liquid_150_mg_5_ml', type: 'Medication', is_enabled: true },
        { name: 'Cefixime Oral Liquid 50 mg/5 ml', key: 'cefixime_oral_liquid_50_mg_5_ml', type: 'Medication', is_enabled: true },
        { name: 'Cefixime Tablet 100 mg', key: 'cefixime_tablet_100_mg', type: 'Medication', is_enabled: true },
        { name: 'Cefixime Tablet 200 mg', key: 'cefixime_tablet_200_mg', type: 'Medication', is_enabled: true },
        { name: 'Cetirizine Oral Liquid 5 mg/5 ml', key: 'cetirizine_oral_liquid_5_mg_5_ml', type: 'Medication', is_enabled: true },
        { name: 'Cetirizine Tablet 10 mg', key: 'cetirizine_tablet_10_mg', type: 'Medication', is_enabled: true },
        { name: 'Chloroquine Oral liquid 50 mg/5 ml', key: 'chloroquine_oral_liquid_50_mg_5_ml', type: 'Medication', is_enabled: true },
        { name: 'Chloroquine Tablet 150 mg', key: 'chloroquine_tablet_150_mg', type: 'Medication', is_enabled: true },
        { name: 'Chlorpheniramine Maleate 2mg+Phenylephrine 5mg Oral Drops (1 ml)', key: 'chlorpheniramine_maleate_2mg_phenylephrine_5mg_oral_drops_1_ml', type: 'Medication', is_enabled: true },
        { name: 'Cholecalciferol Oral Liquid 400 IU/1 ml', key: 'cholecalciferol_oral_liquid_400_IU_1_ml', type: 'Medication', is_enabled: true },
        { name: 'Cholecalciferol Oral Sachet 1000 IU', key: 'cholecalciferol_oral_sachet_1000_IU', type: 'Medication', is_enabled: true },
        { name: 'Ciprofloxacin Eye/Ear Drops 0.3%', key: 'ciprofloxacin_eye_ear_drops_0_3', type: 'Medication', is_enabled: true },
        { name: 'Ciprofloxacin Tablet 250 mg', key: 'ciprofloxacin_tablet_250_mg', type: 'Medication', is_enabled: true },
        { name: 'Ciprofloxacin Tablet 500 mg', key: 'ciprofloxacin_tablet_500_mg', type: 'Medication', is_enabled: true },
        { name: 'Clotrimazole Ear Drops 1%', key: 'clotrimazole_ear_drops_1', type: 'Medication', is_enabled: true },
        { name: 'Clotrimazole Lotion 1%', key: 'clotrimazole_lotion_1', type: 'Medication', is_enabled: true },
        { name: 'Clotrimazole Cream 1%', key: 'clotrimazole_cream_1', type: 'Medication', is_enabled: true },
        { name: 'Clotrimazole Pessary (Vaginal Tablet) 100 mg', key: 'clotrimazole_pessary_vaginal_tablet_100_mg', type: 'Medication', is_enabled: true },
        { name: 'Clotrimazole Mouth Paint 1%', key: 'clotrimazole_mouth_paint_1', type: 'Medication', is_enabled: true },
        { name: 'Colic aid Oral Drops', key: 'colic_aid_oral_drops', type: 'Medication', is_enabled: true },
        { name: 'Co-trimoxazole Tablet (80 mg + 400 mg)', key: 'co_trimoxazole_tablet_80_mg_400_mg', type: 'Medication', is_enabled: true },
        { name: 'Co-trimoxazole Tablet (20 mg + 100 mg)', key: 'co_trimoxazole_tablet_20_mg_100_mg', type: 'Medication', is_enabled: true },
        { name: 'Co-trimoxazole Oral Liquid (40 mg + 200 mg/5 ml)', key: 'co_trimoxazole_oral_liquid_40_mg_200_mg_5_ml', type: 'Medication', is_enabled: true },
        { name: 'Dextromethorphan Oral Liquid 15 mg/5 ml', key: 'dextromethorphan_oral_liquid_15_mg_5_ml', type: 'Medication', is_enabled: true },
        { name: 'Diclofenac Tablet 50 mg', key: 'diclofenac_tablet_50_mg', type: 'Medication', is_enabled: true },
        { name: 'Dicyclomine Tablet 10 mg', key: 'dicyclomine_tablet_10_mg', type: 'Medication', is_enabled: true },
        { name: 'Diethylcarbamazine (DEC) Oral Liquid 120 mg/5 ml', key: 'diethylcarbamazine_dec_oral_liquid_120_mg_5_ml', type: 'Medication', is_enabled: true },
        { name: 'Diethylcarbamazine (DEC) Tablet 100 mg', key: 'diethylcarbamazine_dec_tablet_100_mg', type: 'Medication', is_enabled: true },
        { name: 'Domperidone Oral Liquid 1 mg/1 ml', key: 'domperidone_oral_liquid_1_mg_1_ml', type: 'Medication', is_enabled: true },
        { name: 'Domperidone Tablet 10 mg', key: 'domperidone_tablet_10_mg', type: 'Medication', is_enabled: true },
        { name: 'Doxycycline Capsule 100 mg', key: 'doxycycline_capsule_100_mg', type: 'Medication', is_enabled: true },
        { name: 'Enalapril Tablet 5 mg', key: 'enalapril_tablet_5_mg', type: 'Medication', is_enabled: true },
        { name: 'Folic acid Tablet 1 mg%', key: 'folic_acid_tablet_1_mg', type: 'Medication', is_enabled: true },
        { name: 'Folic acid Tablet 5 mg', key: 'folic_acid_tablet_5_mg', type: 'Medication', is_enabled: true },
        { name: 'Framycetin Cream 1%', key: 'framycetin_cream_1', type: 'Medication', is_enabled: true },
        { name: 'Fluconazole Tablet 100 mg%', key: 'fluconazole_tablet_100_mg', type: 'Medication', is_enabled: true },
        { name: 'Glimepiride Tablet 2 mg', key: 'glimepiride_tablet_2_mg', type: 'Medication', is_enabled: true },
        { name: 'Hydrochlorothiazide Tablet 12.5 mg', key: 'hydrochlorothiazide_tablet_12_5_mg', type: 'Medication', is_enabled: true },
        { name: 'Hydrochlorothiazide Tablet 25 mg', key: 'hydrochlorothiazide_tablet_25_mg', type: 'Medication', is_enabled: true },
        { name: 'Ibuprofen Tablet 400 mg', key: 'ibuprofen_tablet_400_mg', type: 'Medication', is_enabled: true },
        { name: 'Ibuprofen Syrup 100 mg/5 ml', key: 'ibuprofen_syrup_100_mg_5_ml', type: 'Medication', is_enabled: true },
        { name: 'IFA (Ferrous Salt 45 mg + Folic acid 400 mcg) Tablet', key: 'ifa_ferrous_salt_45_mg_folic_acid_400_mcg_tablet', type: 'Medication', is_enabled: true },
        { name: 'IFA (Ferrous Salt 100 mg+ Folic acid 500 mcg) Tablet', key: 'ifa_ferrous_salt_100_mg_folic_acid_500_mcg_tablet', type: 'Medication', is_enabled: true },
        { name: 'IFA (Ferrous Salt 20 mg+ Folic acid 100 mcg) Oral Liquid (1 ml)', key: 'ifa_ferrous_salt_20_mg_folic_acid_100_mcg_oral_liquid_1_ml', type: 'Medication', is_enabled: true },
        { name: 'Junior Lanzol Dispersible Tablet (DT) 15 mg', key: 'junior_lanzol_dispersible_tablet_dt_15_mg', type: 'Medication', is_enabled: true },
        { name: 'Lactulose Oral Liquid 10 g/15 ml', key: 'lactulose_oral_liquid_10_g_15_ml', type: 'Medication', is_enabled: true },
        { name: 'Levocetirizine Tablet 5 mg', key: 'levocetirizine_tablet_5_mg', type: 'Medication', is_enabled: true },
        { name: 'Levocetirizine Oral Liquid 2.5 mg/5 ml', key: 'levocetirizine_oral_liquid_2_5_mg_5_ml', type: 'Medication', is_enabled: true },
        { name: 'Levothyroxine Tablet 25 mcg', key: 'levothyroxine_tablet_25_mcg', type: 'Medication', is_enabled: true },
        { name: 'Levothyroxine Tablet 50 mcg', key: 'levothyroxine_tablet_50_mcg', type: 'Medication', is_enabled: true },
        { name: 'Levothyroxine Tablet 100 mcg', key: 'levothyroxine_tablet_100_mcg', type: 'Medication', is_enabled: true },
        { name: 'Metformin Tablet 500 mg', key: 'metformin_tablet_500_mg', type: 'Medication', is_enabled: true },
        { name: 'Metformin SR Tablet 500 mg', key: 'metformin_sr_tablet_500_mg', type: 'Medication', is_enabled: true },
        { name: 'Metronidazole Tablet 200 mg', key: 'metronidazole_tablet_200_mg', type: 'Medication', is_enabled: true },
        { name: 'Metronidazole Tablet 400 mg', key: 'metronidazole_tablet_400_mg', type: 'Medication', is_enabled: true },
        { name: 'Milk of Magnesia Oral Liquid 8%', key: 'milk_of_magnesia_oral_liquid_8', type: 'Medication', is_enabled: true },
        { name: 'Mupirocin Ointment 2%', key: 'mupirocin_ointment_2', type: 'Medication', is_enabled: true },
        { name: 'Omeprazole Capsule 20 mg', key: 'omeprazole_capsule_20_mg', type: 'Medication', is_enabled: true },
        { name: 'Ondansetron Tablet 4 mg', key: 'ondansetron_tablet_4_mg', type: 'Medication', is_enabled: true },
        { name: 'Ondansetron Oral Liquid 2 mg/5 ml', key: 'ondansetron_oral_liquid_2_mg_5_ml', type: 'Medication', is_enabled: true },
        { name: 'Oral Rehydration Salts (WHO ORS, Large)', key: 'oral_rehydration_salts_who_ors_large', type: 'Medication', is_enabled: true },
        { name: 'Oral Rehydration Salts (WHO ORS, Small)', key: 'oral_rehydration_salts_who_ors_small', type: 'Medication', is_enabled: true },
        { name: 'Paracetamol Oral Drops 100mg/1ml', key: 'paracetamol_oral_drops_100mg_1ml', type: 'Medication', is_enabled: true },
        { name: 'Paracetamol Syrup 125 mg/5ml', key: 'paracetamol_syrup_125_mg_5ml', type: 'Medication', is_enabled: true },
        { name: 'Paracetamol Syrup 250 mg/5ml', key: 'paracetamol_syrup_250_mg_5ml', type: 'Medication', is_enabled: true },
        { name: 'Paracetamol Tablet 500 mg', key: 'paracetamol_tablet_500_mg', type: 'Medication', is_enabled: true },
        { name: 'Paradichlorobenzene 2%+Chlorbutol 5%+Turpentine Oil 15%+ Lidocaine 2% Ear Drops', key: 'paradichlorobenzene_2_chlorbutol_5_turpentine_oil_15_lidocaine_2_ear_drops', type: 'Medication', is_enabled: true },
        { name: 'Permethrin Cream 5%', key: 'permethrin_cream_5', type: 'Medication', is_enabled: true },
        { name: 'Salbutamol Tablet 2 mg', key: 'salbutamol_tablet_2_mg', type: 'Medication', is_enabled: true },
        { name: 'Salbutamol Oral Liquid 2 mg/5 ml', key: 'salbutamol_oral_liquid_2_mg_5_ml', type: 'Medication', is_enabled: true },
        { name: 'Saline Nasal Drops 0.65%', key: 'saline_nasal_drops_0_65', type: 'Medication', is_enabled: true },
        { name: 'Silver Sulphadiazine Cream 1%', key: 'silver_sulphadiazine_cream_1', type: 'Medication', is_enabled: true },
        { name: 'Telmisartan Tablet 40 mg', key: 'telmisartan_tablet_40_mg', type: 'Medication', is_enabled: true },
        { name: 'Xylometazoline Nasal Drops 0.05%', key: 'xylometazoline_nasal_drops_0_05', type: 'Medication', is_enabled: true },
        { name: 'Xylometazoline Nasal Drops 0.1%', key: 'xylometazoline_nasal_drops_0_1', type: 'Medication', is_enabled: true },
        { name: 'Zinc Oxide Cream 10%', key: 'zinc_oxide_cream_10', type: 'Medication', is_enabled: true },
        { name: 'Zinc Sulphate Dispersible Tablet 20 mg', key: 'zinc_sulphate_dispersible_tablet_20_mg', type: 'Medication', is_enabled: true },

        { name: 'Do not smoke bidis or cigarettes', key: 'do_not_smoke_bidis_or_cigarettes', type: 'Advice', is_enabled: true },
        { name: 'Do not drink alcohol', key: 'do_not_drink_alcohol', type: 'Advice', is_enabled: true },
        { name: 'Do not sleep at noon', key: 'do_not_sleep_at_noon', type: 'Advice', is_enabled: true },
        { name: 'Do not eat stale foods and fermented rice', key: 'do_not_eat_stale_foods_and_fermented_rice', type: 'Advice', is_enabled: true },
        { name: 'Do not walk barefoot', key: 'do_not_walk_barefoot', type: 'Advice', is_enabled: true },
        { name: 'Follow diabetic food chart', key: 'follow_diabetic_food_chart', type: 'Advice', is_enabled: true },
        { name: 'Do not eat raw salt', key: 'do_not_eat_raw_salt', type: 'Advice', is_enabled: true },
        { name: 'Eat hot meals', key: 'eat_hot_meals', type: 'Advice', is_enabled: true },
        { name: 'Eat foods cooked without salt', key: 'eat_foods_cooked_without_salt', type: 'Advice', is_enabled: true },
        { name: 'Lower sodium intake', key: 'lower_sodium_intake', type: 'Advice', is_enabled: true },
        { name: 'Stay neat and clean', key: 'stay_neat_and_clean', type: 'Advice', is_enabled: true },
        { name: 'Do not close all the doors and windows while sleeping', key: 'do_not_close_all_doors_and_windows_while_sleeping', type: 'Advice', is_enabled: true },
        { name: 'Drink less water', key: 'drink_less_water', type: 'Advice', is_enabled: true },
        { name: 'Do not eat raw onion', key: 'do_not_eat_raw_onion', type: 'Advice', is_enabled: true },
        { name: 'Do not eat raw tomato, lettuce, or lentil', key: 'do_not_eat_raw_tomato_lettuce_or_lentil', type: 'Advice', is_enabled: true },
        { name: 'Drink lots of water', key: 'drink_lots_of_water', type: 'Advice', is_enabled: true },
        { name: 'Drink cooled boiled drinking water', key: 'drink_cooled_boiled_drinking_water', type: 'Advice', is_enabled: true },
        { name: 'Wear dry clothes after bath', key: 'wear_dry_clothes_after_bath', type: 'Advice', is_enabled: true },
        { name: 'Do not do heavy work', key: 'do_not_do_heavy_work', type: 'Advice', is_enabled: true },
        { name: 'Do not brush your teeth with gurakhu', key: 'do_not_brush_teeth_with_gurakhu', type: 'Advice', is_enabled: true },
        { name: 'Eat plenty of green leafy vegetables and fruits', key: 'eat_plenty_of_green_leafy_vegetables_and_fruits', type: 'Advice', is_enabled: true },
        { name: 'Avoid oily and spicy foods', key: 'avoid_oily_and_spicy_foods', type: 'Advice', is_enabled: true },
        { name: 'Exercise daily', key: 'exercise_daily', type: 'Advice', is_enabled: true },
        { name: 'Review with diagnostic report', key: 'review_with_diagnostic_report', type: 'Advice', is_enabled: true },
        { name: 'Gurgle with lukewarm saline water', key: 'gurgle_with_lukewarm_saline_water', type: 'Advice', is_enabled: true },
        { name: 'Do not study in low light', key: 'do_not_study_in_low_light', type: 'Advice', is_enabled: true },
        { name: 'Maintain good personal hygiene', key: 'maintain_good_personal_hygiene', type: 'Advice', is_enabled: true },
        { name: 'Regular hand washing with soap and water', key: 'regular_hand_washing_with_soap_and_water', type: 'Advice', is_enabled: true },
        { name: 'Cough etiquette & respiratory hygiene', key: 'cough_etiquette_and_respiratory_hygiene', type: 'Advice', is_enabled: true },
        { name: 'Immunization as per recommended schedule', key: 'immunization_as_per_recommended_schedule', type: 'Advice', is_enabled: true },
        { name: 'Follow safe food handling practices', key: 'follow_safe_food_handling_practices', type: 'Advice', is_enabled: true },
        { name: 'Avoid close contact with individuals who have contagious illnesses', key: 'avoid_close_contact_with_individuals_who_have_contagious_illnesses', type: 'Advice', is_enabled: true },
        { name: 'Adopt healthy lifestyle', key: 'adopt_healthy_lifestyle', type: 'Advice', is_enabled: true },
        { name: 'Balanced diet', key: 'balanced_diet', type: 'Advice', is_enabled: true },
        { name: 'Regular physical exercise', key: 'regular_physical_exercise', type: 'Advice', is_enabled: true },
        { name: 'Avoid tobacco chewing (khaini, zarda & gutka)', key: 'avoid_tobacco_chewing', type: 'Advice', is_enabled: true },
        { name: 'Avoid tobacco smoking', key: 'avoid_tobacco_smoking', type: 'Advice', is_enabled: true },
        { name: 'Limit alcohol consumption', key: 'limit_alcohol_consumption', type: 'Advice', is_enabled: true },
        { name: 'Get regular health check-ups', key: 'get_regular_health_checkups', type: 'Advice', is_enabled: true },
        { name: 'Get regular annual/periodic screenings for non-communicable diseases', key: 'get_regular_screenings_for_non_communicable_diseases', type: 'Advice', is_enabled: true },
        { name: 'Manage stress through relaxation techniques & emotional well-being', key: 'manage_stress_through_relaxation_techniques', type: 'Advice', is_enabled: true },
        { name: 'Reduce body weight', key: 'reduce_body_weight', type: 'Advice', is_enabled: true },
        { name: 'Consume salt less than a teaspoon (5g) in a day', key: 'consume_salt_less_than_5g_in_a_day', type: 'Advice', is_enabled: true },
        { name: 'Healthy timing and spacing of pregnancy (HTSP)', key: 'healthy_timing_and_spacing_of_pregnancy', type: 'Advice', is_enabled: true },
        { name: 'Take folic acid supplementation during planning for pregnancy', key: 'take_folic_acid_supplementation', type: 'Advice', is_enabled: true },
        { name: 'Attend for regular antenatal check-ups', key: 'attend_regular_antenatal_checkups', type: 'Advice', is_enabled: true },
        { name: 'Avoid the consumption of unprescribed drugs', key: 'avoid_consumption_of_unprescribed_drugs', type: 'Advice', is_enabled: true },
        { name: 'Avoid exposure to passive smoking', key: 'avoid_exposure_to_passive_smoking', type: 'Advice', is_enabled: true },
        { name: 'Exclusive breastfeeding till 6 months of age', key: 'exclusive_breastfeeding_till_6_months_of_age', type: 'Advice', is_enabled: true },
        { name: 'Start complimentary feeding after 6 months of age', key: 'start_complimentary_feeding_after_6_months', type: 'Advice', is_enabled: true },
        { name: 'Continue to breastfeed in addition to complimentary feeding till 2 years', key: 'continue_to_breastfeed_till_2_years', type: 'Advice', is_enabled: true },
        { name: 'Age appropriate, frequent calorie dense feeds', key: 'age_appropriate_frequent_calorie_dense_feeds', type: 'Advice', is_enabled: true },
        { name: 'Clean feeding practices', key: 'clean_feeding_practices', type: 'Advice', is_enabled: true },
        { name: 'Avoid bottle feeding', key: 'avoid_bottle_feeding', type: 'Advice', is_enabled: true },
        { name: 'Avoid harmful practices', key: 'avoid_harmful_practices', type: 'Advice', is_enabled: true },
        { name: 'Use mosquito nets', key: 'use_mosquito_nets', type: 'Advice', is_enabled: true },
        { name: 'Avoid eating junk, oily & spicy foods', key: 'avoid_eating_junk_oily_spicy_foods', type: 'Advice', is_enabled: true },
        { name: 'Warmth care', key: 'warmth_care', type: 'Advice', is_enabled: true },
        { name: 'Care of umbilical cord', key: 'care_of_umbilical_cord', type: 'Advice', is_enabled: true },
        { name: 'Avoid nail biting', key: 'avoid_nail_biting', type: 'Advice', is_enabled: true },
        { name: 'Wear footwear outdoors', key: 'wear_footwear_outdoors', type: 'Advice', is_enabled: true },
        { name: 'Avoid lifting heavy weights', key: 'avoid_lifting_heavy_weights', type: 'Advice', is_enabled: true },
        { name: 'Brush teeth twice a day using soft bristles', key: 'brush_teeth_twice_a_day_using_soft_bristles', type: 'Advice', is_enabled: true },
        { name: 'Care of feet', key: 'care_of_feet', type: 'Advice', is_enabled: true },
        { name: 'Limit screen watching time to less than 2 hours in a day', key: 'limit_screen_watching_time', type: 'Advice', is_enabled: true },
        { name: 'Avoid exposure to hot weather', key: 'avoid_exposure_to_hot_weather', type: 'Advice', is_enabled: true },
        { name: 'Review with test reports', key: 'review_with_test_reports', type: 'Advice', is_enabled: true },
        { name: 'Test-Advice-Malaria', key: 'test_advice_malaria', type: 'Advice', is_enabled: true },

        { name: 'HSC', key: 'hsc', type: 'Referral Facility', is_enabled: true },
        { name: 'PHC', key: 'phc', type: 'Referral Facility', is_enabled: true },
        { name: 'CHC', key: 'chc', type: 'Referral Facility', is_enabled: true },
        { name: 'SDH', key: 'sdh', type: 'Referral Facility', is_enabled: true },
        { name: 'DH', key: 'dh', type: 'Referral Facility', is_enabled: true },
        { name: 'TH', key: 'th', type: 'Referral Facility', is_enabled: true },
        { name: 'GH', key: 'gh', type: 'Referral Facility', is_enabled: true },
        { name: 'Private Hospital', key: 'private_hospital', type: 'Referral Facility', is_enabled: true }
      ]);
    }),

  down: (queryInterface: QueryInterface): Promise<void> => queryInterface.sequelize.transaction(
    async (transaction) => {
      /**
       * Add commands to revert seed here.
       *
       * Example:
       * await queryInterface.bulkDelete('People', null, {});
       */
      await queryInterface.bulkDelete('mst_dropdown_values', {}, { transaction });
    })
};
