version: '3.8'

services:
  app:
    image: ghcr.io/your-username/nodejs-docker-github-action:latest
    ports:
      - "3004:3004"
    environment:
      - NODE_ENV=production
      - PORT=3004
      - HOSTNAME=0.0.0.0
    volumes:
      # Mount .env file from host to container (optional)
      - /home/deploy/portal/.env:/app/.env:ro
    restart: unless-stopped
    container_name: portal
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3004/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  app-network:
    driver: bridge

