module.exports = {
    FROM_DATE: 'fromDate',
    TO_DATE: 'toDate',
    LOCATION_UUID: 'locationUuid',
    SPECIALITY: "speciality",
    SLOT_DAY: 'slotDay',
    SLOT_DURATION: 'slotDuration',
    SLOT_DURATION_UNIT: 'slotDurationUnit',
    SLOT_SCHEDULE: 'slotSchedule',
    SLOT_TIME: 'slotTime',
    USER_UUID: 'userUuid',
    DR_NAME: 'drName',
    VISIT_UUID: 'visitUuid',
    PATIENT_NAME: 'patientName',
    OPEN_MRS_ID: 'openMrsId',
    HW_UUID: 'hwUUID',
    APPOINTMENT_ID: 'appointmentId',
    ID: 'id',
    DAYS_OFF: 'daysOff',
    MONTH: 'month',
    YEAR: 'year',
    TYPE: 'type',
    START_DATE: 'startDate',
    END_DATE: 'endDate',
    FROM_USER: 'fromUser',
    TO_USER: 'toUser',
    PATIENT_ID: 'patientId',
    MESSAGE: 'message',
    MESSAGE_ID: 'messageId',
    KEY_NAME: "keyName",
    EXPIRY: "expiry",
    IMAGE_VALUE: "imageValue",
    IMAGE_NAME: "imageName",
    FILE: 'file',
    PROVIDER_ID: 'providerId',
    TEXT_OF_SIGN: 'textOfSign',
    FONT_NAME: 'fontName',
    CANCELLED: "cancelled",
    SLOT_JS_DATE: "slotJsDate",
    RESCHEDULED: "rescheduled",
    BOOKED: "booked",
    CREATED_AT: "createdAt",
    UPDATED_AT: "updatedAt",
    COMPLETED: "completed",
    DAYS: "days",
    USERNAME: "username",
    PASSWORD: "password",
    VERIFICATON: "verificaton",
    PHONE_NUMBER: "phoneNumber",
    COUNTRY_CODE: "countryCode",
    EMAIL_ID: "emailId",
    VISIT_TYPES: {
        PRIORITY: 'Priority',
        AWAITING:'Awaiting Consult',
        IN_PROGRESS:'Visit In Progress',
        ENDED: 'Ended Visit',
        FOLLOW_UP:'Follow-Up'
    },
    RESOURCE_TYPE: 'resource_type',
    RESOURCE_ID: 'resource_id',
    PARENT_ID: 'parent_id',
    PARENT_TYPE: 'parent_type',
    DATA: 'data',
    CREATED_BY: 'created_by',
    SYNC_STATUS: 'sync_status',
    RESOURCE_TYPES: {
        PATIENT: 'patient',
        VISIT: 'visit',
        ASSET: 'asset'
    },
    SYNC_STATUSES: {
        PENDING: 'pending',
        SYNCED: 'synced'
    },
    TEMP_STORAGE: {
        UPLOAD_FOLDER: 'temp_storage',
        DEFAULT_SYNCED_RETENTION_DAYS: 7,
        DEFAULT_UNSYNCED_RETENTION_DAYS: 30,
        MS_PER_DAY: 24 * 60 * 60 * 1000,
        CLEANUP_ORDER: ['asset', 'visit', 'patient']
    },
    SORT_ORDER: {
        ASC: 'ASC',
        DESC: 'DESC'
    },
    PENDING_VISIT_BY_CALL_STATUS: [
        "Review of Imaging", 
        "Review with Reports",
        "Referral", 
        "Close Call without Completion", 
        "Reschedule/Repeat Internally"
    ]
}
