module.exports = {
    FROM_DATE: 'fromDate',
    TO_DATE: 'toDate',
    LOCATION_UUID: 'locationUuid',
    SPECIALITY: "speciality",
    SLOT_DAY: 'slotDay',
    SLOT_DURATION: 'slotDuration',
    SLOT_DURATION_UNIT: 'slotDurationUnit',
    SLOT_SCHEDULE: 'slotSchedule',
    SLOT_TIME: 'slotTime',
    USER_UUID: 'userUuid',
    DR_NAME: 'drName',
    VISIT_UUID: 'visitUuid',
    PATIENT_NAME: 'patientName',
    OPEN_MRS_ID: 'openMrsId',
    HW_UUID: 'hwUUID',
    APPOINTMENT_ID: 'appointmentId',
    ID: 'id',
    DAYS_OFF: 'daysOff',
    MONTH: 'month',
    YEAR: 'year',
    TYPE: 'type',
    START_DATE: 'startDate',
    END_DATE: 'endDate',
    FROM_USER: 'fromUser',
    TO_USER: 'toUser',
    PATIENT_ID: 'patientId',
    MESSAGE: 'message',
    MESSAGE_ID: 'messageId',
    KEY_NAME: "keyName",
    EXPIRY: "expiry",
    IMAGE_VALUE: "imageValue",
    IMAGE_NAME: "imageName",
    FILE: 'file',
    PROVIDER_ID: 'providerId',
    TEXT_OF_SIGN: 'textOfSign',
    FONT_NAME: 'fontName',
    CANCELLED: "cancelled",
    SLOT_JS_DATE: "slotJsDate",
    RESCHEDULED: "rescheduled",
    BOOKED: "booked",
    CREATED_AT: "createdAt",
    UPDATED_AT: "updatedAt",
    COMPLETED: "completed",
    DAYS: "days",
    USERNAME: "username",
    PASSWORD: "password",
    VERIFICATON: "verificaton",
    PHONE_NUMBER: "phoneNumber",
    COUNTRY_CODE: "countryCode",
    EMAIL_ID: "emailId",
    VISIT_TYPES: {
        PRIORITY: 'Priority',
        AWAITING:'Awaiting Consult',
        IN_PROGRESS:'Visit In Progress',
        ENDED: 'Ended Visit',
        FOLLOW_UP:'Follow-Up'
    }
}
