// Turn's abdominal-pain journey sends answers nested under `abdominal_pain`.
// Each entry maps one payload key -> the label shown under the Chief Complaint,
// in display order.
module.exports = [
   ["start_time",               "Pain started"],
   ["hours",                    "Duration (hours)"],
   ["days",                     "Duration (days)"],
   ["weeks",                    "Duration (weeks)"],
   ["onset",                    "Onset"],
   ["location",                 "Location"],
   ["site",                     "Site"],
   ["site_more",                "Site (more)"],
   ["character",                "Character"],
   ["severity",                 "Severity"],
   ["relieving_factors",        "Relieving factors"],
   ["aggravating_factors",      "Aggravating factors"],
   ["progression",              "Progression"],
   ["constant_intermittent",    "Constant / intermittent"],
   ["diurnal_variation",        "Diurnal variation"],
   ["radiates",                 "Radiates"],
   ["radiates_to",              "Radiates to"],
   ["radiates_to_2",            "Radiates to (2)"],
   ["radiates_to_3",            "Radiates to (3)"],
   ["assoc_distention",         "Associated: distention"],
   ["assoc_vomiting",           "Associated: vomiting"],
   ["vomit_character",          "Vomit character"],
   ["assoc_belching",           "Associated: belching"],
   ["assoc_heartburn",          "Associated: heartburn"],
   ["assoc_jaundice",           "Associated: jaundice"],
   ["assoc_constipation",       "Associated: constipation"],
   ["assoc_diarrhea",           "Associated: diarrhea"],
   ["assoc_blood_stools",       "Associated: blood in stools"],
   ["assoc_black_stools",       "Associated: black stools"],
   ["assoc_loss_appetite",      "Associated: loss of appetite"],
   ["assoc_increased_appetite", "Associated: increased appetite"],
   ["assoc_weight_loss",        "Associated: weight loss"],
   ["assoc_injury_abdomen",     "Associated: injury to abdomen"],
];
