name: Portal GHCR Deploy

on:
  push:
    branches: [development_master]  
    paths:
      - 'portal/**'
  workflow_dispatch:

env:
  DOCKER_IMAGE_NAME: portal
  # Use GitHub's built-in variables for the registry path
  IMAGE_TAG: ghcr.io/${{ github.repository }}/portal:${{ github.sha }} 
  REMOTE_HOST: ${{secrets.DEV_HOST}}
  REMOTE_USER: ${{secrets.DEV_USER}}
  REMOTE_PORT: 22
  DEPLOY_ENV_FILE_PATH: /home/ubuntu/deploy/portal/.env
  DEPLOY_PEM_FOLDER_PATH: /home/ubuntu/deploy/portal/.pem
  PORTAL_DIR: portal

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    # Define an environment in GitHub for better secret management
    environment: dev 
    
    # Permissions required to read/write to GHCR (packages)
    permissions:
      contents: read
      packages: write
      
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
     
    # --------------------------------------------------------------------------
    # Build and Push Stage (Replaces SCP/Save)
    # --------------------------------------------------------------------------

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: ${{ env.PORTAL_DIR }}/package-lock.json

    - name: Install dependencies
      run: npm ci
      working-directory: ${{ env.PORTAL_DIR }} 
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        # Use the built-in GITHUB_TOKEN for authentication
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and Push Docker image to GHCR
      uses: docker/build-push-action@v5
      with:
        context: ${{ env.PORTAL_DIR }}
        push: true
        tags: ${{ env.IMAGE_TAG }}
        # Optional: Add build cache for faster subsequent builds
        cache-from: type=gha
        cache-to: type=gha,mode=max

    # --------------------------------------------------------------------------
    # Deployment Stage (Pull and Run)
    # --------------------------------------------------------------------------
    
    # We no longer need the 'scp-action' as the file transfer is handled by GHCR

    - name: Run deployment commands on remote host
      # This action is used to execute remote SSH commands
      uses: appleboy/ssh-action@v1.0.1 
      with:
        host: ${{ env.REMOTE_HOST }}
        username: ${{ env.REMOTE_USER }}
        port: ${{ env.REMOTE_PORT }}
        key: ${{ secrets.DEV_SSH_KEY }}
        script: |
          DOCKER_IMAGE_NAME="${{ env.DOCKER_IMAGE_NAME }}"
          IMAGE_TAG="${{ env.IMAGE_TAG }}" # The full GHCR tag
          ENV_FILE_PATH="${{ env.DEPLOY_ENV_FILE_PATH }}"
          PEM_FOLDER_PATH="${{ env.DEPLOY_PEM_FOLDER_PATH }}"
          
          echo "Starting deployment for image $IMAGE_TAG"

          # 1. Log in to GHCR on the remote host (Needed for private images)
          # Use a dedicated deployment token (DEV_GHCR_TOKEN) with 'read:packages' scope
          # Store this token as a separate secret for better security than an SSH key.
          docker login ghcr.io -u ${{ env.REMOTE_USER }} -p ${{ secrets.DEV_GHCR_TOKEN }}

          # 2. Stop and remove existing container
          docker stop $DOCKER_IMAGE_NAME || true
          docker rm -f $DOCKER_IMAGE_NAME || true
          
          # 3. Pull the image from GHCR
          docker pull $IMAGE_TAG
          
          # 4. Clean up login credentials immediately
          docker logout ghcr.io

          # Verification checks (same as before)
          if [ ! -f "$ENV_FILE_PATH" ]; then
              echo "Error: .env file not found at $ENV_FILE_PATH. Exiting."
              exit 1
          fi
          
          if [ ! -d "$PEM_FOLDER_PATH" ]; then
              echo "Error: .pem folder not found at $PEM_FOLDER_PATH. Exiting."
              exit 1
          fi
          
          # 5. Run new container
          docker run -d \
              --name $DOCKER_IMAGE_NAME \
              --restart unless-stopped \
              -p 3004:3004 \
              --env-file $ENV_FILE_PATH \
              -v $PEM_FOLDER_PATH:/app/.pem:ro \
              --mount type=bind,src=/etc/letsencrypt,dst=/etc/letsencrypt,ro \
              $IMAGE_TAG
          
          # Clean up old images
          docker image prune -f
          
          echo "Portal deployment completed successfully using GHCR pull"

    # --------------------------------------------------------------------------
    # Verification Stage
    # --------------------------------------------------------------------------
    
    - name: Verify deployment
      uses: appleboy/ssh-action@v1.0.1
      with:
        host: ${{ env.REMOTE_HOST }}
        username: ${{ env.REMOTE_USER }}
        port: ${{ env.REMOTE_PORT }}
        key: ${{ secrets.DEV_SSH_KEY }}
        script: |
          if docker ps -f name=${{ env.DOCKER_IMAGE_NAME }} | grep ${{ env.DOCKER_IMAGE_NAME }}; then
            echo "Portal container is running successfully!"
          else
            echo "Portal container is NOT running. Check remote logs."
            exit 1 # Fail the step if the container isn't running
          fi
